Class Fitbit.Api.Client.responses.getProfile Extends Fitbit.Api.Client.responses.GenericResponse
{

XData profilesample [ MimeType = application/json ]
{
{
	"user": {
		"age": 60,
		"ambassador": false,
		"autoStrideEnabled": false,
		"avatar": "https://static0.fitbit.com/images/profile/defaultProfile_100.png",
		"avatar150": "https://static0.fitbit.com/images/profile/defaultProfile_150.png",
		"avatar640": "https://static0.fitbit.com/images/profile/defaultProfile_640.png",
		"averageDailySteps": 10142,
		"challengesBeta": true,
		"clockTimeDisplayFormat": "12hour",
		"corporate": false,
		"corporateAdmin": false,
		"country": "NL",
		"dateOfBirth": "1963-08-26",
		"displayName": "Theo S.",
		"displayNameSetting": "name",
		"distanceUnit": "METRIC",
		"encodedId": "4D8CR2",
		"features": {
			"exerciseGoal": true
		},
		"firstName": "Theo",
		"foodsLocale": "en_US",
		"fullName": "Theo Stolker",
		"gender": "MALE",
		"glucoseUnit": "en_US",
		"height": 197.0,
		"heightUnit": "METRIC",
		"isBugReportEnabled": false,
		"isChild": false,
		"isCoach": false,
		"languageLocale": "nl_NL",
		"lastName": "Stolker",
		"legalTermsAcceptRequired": true,
		"locale": "nl_NL",
		"memberSince": "2016-03-10",
		"mfaEnabled": false,
		"offsetFromUTCMillis": 3600000,
		"sdkDeveloper": true,
		"sleepTracking": "Normal",
		"startDayOfWeek": "SUNDAY",
		"strideLengthRunning": 105.80000000000001,
		"strideLengthRunningType": "manual",
		"strideLengthWalking": 81.80000000000001,
		"strideLengthWalkingType": "manual",
		"swimUnit": "METRIC",
		"temperatureUnit": "en_US",
		"timezone": "Europe/Amsterdam",
		"topBadges": [
			{
				"badgeGradientEndColor": "FFDB01",
				"badgeGradientStartColor": "D99123",
				"badgeType": "DAILY_STEPS",
				"category": "Daily Steps",
				"cheers": [],
				"dateTime": "2016-10-29",
				"description": "25,000 steps in a day",
				"earnedMessage": "Congrats on earning your first Classics badge!",
				"encodedId": "228TLX",
				"image100px": "https://www.gstatic.com/fitbit/badge/images/badges_new/100px/badge_daily_steps25k.png",
				"image125px": "https://www.gstatic.com/fitbit/badge/images/badges_new/125px/badge_daily_steps25k.png",
				"image300px": "https://www.gstatic.com/fitbit/badge/images/badges_new/300px/badge_daily_steps25k.png",
				"image50px": "https://www.gstatic.com/fitbit/badge/images/badges_new/badge_daily_steps25k.png",
				"image75px": "https://www.gstatic.com/fitbit/badge/images/badges_new/75px/badge_daily_steps25k.png",
				"marketingDescription": "You've walked 25,000 steps  And earned the Classics badge!",
				"mobileDescription": "With this impressive fitness feat, you've added a badge to your growing collection. Nice job, you stepping all-star!",
				"name": "Classics (25,000 steps in a day)",
				"shareImage640px": "https://www.gstatic.com/fitbit/badge/images/badges_new/386px/shareLocalized/en_US/badge_daily_steps25k.png",
				"shareText": "I took 25,000 steps and earned the Classics badge! #Fitbit",
				"shortDescription": "25,000 steps",
				"shortName": "Classics",
				"timesAchieved": 1,
				"value": 25000
			},
			{
				"badgeGradientEndColor": "00A0E5",
				"badgeGradientStartColor": "0056A3",
				"badgeType": "LIFETIME_DISTANCE",
				"category": "Lifetime Distance",
				"cheers": [],
				"dateTime": "2022-03-13",
				"description": "12,713 lifetime kilometers",
				"earnedMessage": "Whoa! You've earned the Earth badge!",
				"encodedId": "22B8L4",
				"image100px": "https://www.gstatic.com/fitbit/badge/images/badges_new/100px/badge_lifetime_miles7900.png",
				"image125px": "https://www.gstatic.com/fitbit/badge/images/badges_new/125px/badge_lifetime_miles7900.png",
				"image300px": "https://www.gstatic.com/fitbit/badge/images/badges_new/300px/badge_lifetime_miles7900.png",
				"image50px": "https://www.gstatic.com/fitbit/badge/images/badges_new/badge_lifetime_miles7900.png",
				"image75px": "https://www.gstatic.com/fitbit/badge/images/badges_new/75px/badge_lifetime_miles7900.png",
				"marketingDescription": "By reaching 12,713 lifetime kilometers, you've earned the Earth badge!",
				"mobileDescription": "By walking a distance that's akin to taking a journey through the center of the earth, you proved you've got commitment to the core.",
				"name": "Earth (12,713 lifetime kilometers)",
				"shareImage640px": "https://www.gstatic.com/fitbit/badge/images/badges_new/386px/shareLocalized/en_US/badge_lifetime_miles7900_km.png",
				"shareText": "I covered 12,713 kilometers with my #Fitbit and earned the Earth badge.",
				"shortDescription": "12,713 kilometers",
				"shortName": "Earth",
				"timesAchieved": 1,
				"unit": "KILOMETERS",
				"value": 12713
			},
			{
				"badgeGradientEndColor": "FFDB01",
				"badgeGradientStartColor": "D99123",
				"badgeType": "DAILY_FLOORS",
				"category": "Daily Climb",
				"cheers": [],
				"dateTime": "2020-07-28",
				"description": "75 floors in a day",
				"earnedMessage": "Congrats on earning your first Ferris Wheel badge!",
				"encodedId": "229843",
				"image100px": "https://www.gstatic.com/fitbit/badge/images/badges_new/100px/badge_daily_floors75.png",
				"image125px": "https://www.gstatic.com/fitbit/badge/images/badges_new/125px/badge_daily_floors75.png",
				"image300px": "https://www.gstatic.com/fitbit/badge/images/badges_new/300px/badge_daily_floors75.png",
				"image50px": "https://www.gstatic.com/fitbit/badge/images/badges_new/badge_daily_floors75.png",
				"image75px": "https://www.gstatic.com/fitbit/badge/images/badges_new/75px/badge_daily_floors75.png",
				"marketingDescription": "You've climbed 75 floors to earn the Ferris Wheel badge!",
				"mobileDescription": "Put your hands up, celebrate, and enjoy the ride!",
				"name": "Ferris Wheel (75 floors in a day)",
				"shareImage640px": "https://www.gstatic.com/fitbit/badge/images/badges_new/386px/shareLocalized/en_US/badge_daily_floors75.png",
				"shareText": "I climbed 75 flights of stairs and earned the Ferris Wheel badge! #Fitbit",
				"shortDescription": "75 floors",
				"shortName": "Ferris Wheel",
				"timesAchieved": 3,
				"value": 75
			},
			{
				"badgeGradientEndColor": "00A0E5",
				"badgeGradientStartColor": "0056A3",
				"badgeType": "LIFETIME_FLOORS",
				"category": "Lifetime Climb",
				"cheers": [],
				"dateTime": "2021-10-27",
				"description": "28,000 lifetime floors",
				"earnedMessage": "Yipee! You've earned the Astronaut badge!",
				"encodedId": "228TJX",
				"image100px": "https://www.gstatic.com/fitbit/badge/images/badges_new/100px/badge_lifetime_floors28k.png",
				"image125px": "https://www.gstatic.com/fitbit/badge/images/badges_new/125px/badge_lifetime_floors28k.png",
				"image300px": "https://www.gstatic.com/fitbit/badge/images/badges_new/300px/badge_lifetime_floors28k.png",
				"image50px": "https://www.gstatic.com/fitbit/badge/images/badges_new/badge_lifetime_floors28k.png",
				"image75px": "https://www.gstatic.com/fitbit/badge/images/badges_new/75px/badge_lifetime_floors28k.png",
				"marketingDescription": "By climbing 28000 lifetime floors, you've earned the Astronaut badge!",
				"mobileDescription": "That's as high as an astronaut goes. It doesn't take a rocket scientist to see you're crushing it!",
				"name": "Astronaut (28,000 lifetime floors)",
				"shareImage640px": "https://www.gstatic.com/fitbit/badge/images/badges_new/386px/shareLocalized/en_US/badge_lifetime_floors28k.png",
				"shareText": "I climbed 28,000 floors with my #Fitbit and earned the Astronaut badge.",
				"shortDescription": "28,000 floors",
				"shortName": "Astronaut",
				"timesAchieved": 1,
				"value": 28000
			}
		],
		"visibleUser": true,
		"waterUnit": "METRIC",
		"waterUnitName": "ml",
		"weight": 100.9,
		"weightUnit": "METRIC"
	}
}
}

/// http status code = 200 content-type = application/json
Property User As Fitbit.Api.Client.model.User;

/// Description
ClassMethod Test()
{
	set user = ##class(Fitbit.Api.Client.model.User).%New()
	set sc = user.%JSONImport(##class(%Dictionary.XDataDefinition).%OpenId($CLASSNAME() _ "||profilesample").Data)

	if $$$ISERR(sc)
	{
		w "JSONImport(): " _ $SYSTEM.Status.GetErrorText(sc)
	}

	set sc =  user.%JSONExportToString(.json)

	if $$$ISERR(sc)
	{
		w "JSONExportToString(): " _ $SYSTEM.Status.GetErrorText(sc)
	}

	w json
}

/// Implement operationId : getProfile
/// get /1/user/-/profile.json
Method LoadFromResponse(httpResponse As %Net.HttpResponse, caller As %String = "") As %Status
{
	set sc = $$$OK
	do ##super(httpResponse, caller)

	if $$$LOWER($Piece(httpResponse.ContentType,";",1))="application/json",httpResponse.StatusCode = "200"
	{
		set ..User = ##class(Fitbit.Api.Client.model.User).%New()
		set ..status = ..User.%JSONImport(httpResponse.Data)

		return sc
	}

	return sc
}

Storage Default
{
<Data name="getProfileDefaultData">
<Subscript>"getProfile"</Subscript>
<Value name="1">
<Value>User</Value>
</Value>
</Data>
<DefaultData>getProfileDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
